name: image_picker_windows
description: Windows platform implementation of image_picker
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.2.1+1
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      windows:
        dartPluginClass: ImagePickerWindows

dependencies:
  file_selector_platform_interface:
    git:
      url: https://github.com/windata-tech/wd_image_picker.git
      ref: main
      path: packages/file_selector/file_selector_platform_interface/
  file_selector_windows:
    git:
      url: https://github.com/windata-tech/wd_image_picker.git
      ref: main
      path: packages/file_selector/file_selector_windows/
  flutter:
    sdk: flutter
#  image_picker_platform_interface: ^2.8.0
  image_picker_platform_interface:
    path: ../image_picker_platform_interface/

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - image-picker
  - files
  - file-selection
