name: file_selector
description: Flutter plugin for opening and saving files, or selecting
  directories, using native file selection UI.
repository: https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 1.0.3

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: file_selector_android
      ios:
        default_package: file_selector_ios
      linux:
        default_package: file_selector_linux
      macos:
        default_package: file_selector_macos
      web:
        default_package: file_selector_web
      windows:
        default_package: file_selector_windows

dependencies:
  file_selector_android:
    path: ../file_selector_android
  file_selector_ios:
    path: ../file_selector_ios
  file_selector_linux:
    path: ../file_selector_linux
  file_selector_macos:
    path: ../file_selector_macos
  file_selector_platform_interface:
    path: ../file_selector_platform_interface
#  file_selector_test: ^0.9.1
  file_selector_web:
    path: ../file_selector_web
  file_selector_windows:
    path: ../file_selector_windows
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  test: ^1.16.3

topics:
  - files
  - file-selection
  - file-selector
